Update llama-cpp-9999.ebuild The rpc server binary was renamed in upstream.
fixes !!! dobin: /var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999_build/bin/rpc-server does not exist

ERROR: sci-misc/llama-cpp-9999::guru failed (install phase):

dobin failed


If you need support, post the output of emerge --info '=sci-misc/llama-cpp-9999::guru',

the complete build log and the output of emerge -pqv '=sci-misc/llama-cpp-9999::guru'.

The complete build log is located at '/var/tmp/portage/sci-misc/llama-cpp-9999/temp/build.log'.

The ebuild environment file is located at '/var/tmp/portage/sci-misc/llama-cpp-9999/temp/environment'.

Working directory: '/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999'

S: '/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999'

QA Notice: file does not exist:


dobin: /var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999_build/bin/rpc-server does not exist

>>> Failed to emerge sci-misc/llama-cpp-9999, Log file:

>>> '/var/tmp/portage/sci-misc/llama-cpp-9999/temp/build.log'