www-apps/zola: link webp dynamically, enable cjk support, add shell-completion
- Upstream's Cargo.lock has a very old version of libwebp-sys because of
  webp[1] crate. Update with `cargo_update_crates` and enable dynamic linking
  or else builds might fail[2].

- Upstream disables indexing cjk support by default to reduce the binary size
  (40M vs 116M) for their releases.

- pkg-config needed by oniguruma:
```
  error: failed to run custom build command for `onig_sys v69.9.1`
  ...
  Unable to find oniguruma in pkg-config, and RUSTONIG_SYSTEM_LIBONIG is set:
  Could not run `PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
  PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags oniguruma 'oniguruma >= 6.9.3'`
  The pkg-config command could not be found.
```

- pkg-config also needed with the updated libwebp-sys (old versions don't):

[1]: https://github.com/jaredforth/webp/issues/50
[2]: https://bugs.gentoo.org/947693#c16

Signed-off-by: zyxhere💭 <zyx@envs.net>