net-im/chatterino: fix missing bundled deps in 9999
This fix the following build error :
> In file included from /var/tmp/portage/net-im/chatterino-9999/
>    work/chatterino-9999/src/Application.cpp:40:
> /var/tmp/portage/net-im/chatterino-9999/work/chatterino-9999/
>    src/messages/MessageBuilder.hpp:13:10: fatal error:
>       IrcTagsRef: No such file or directory
>    13 | #include <IrcTagsRef>
>       |          ^~~~~~~~~~~~
> compilation terminated.

Build fails since upstream commit:
   aba6e69fb11a58c63173fbcdb69f45f28ca4d490

Signed-off-by: Fabrice Delliaux <netbox253@netc.eu>