dev-util/xrt: fix missing dependency ms-gsl
error: /var/tmp/portage/dev-util/xrt-2.21.75/work/XRT-2.21.75/src/runtime_src/core/common/scheduler.cpp:18:10: fatal error: gsl/pointers: No such file or directory

Signed-off-by: Nausill_on <Nausill_on@proton.me>